export default {
    content: [
        './resources/views/**/*.blade.php',
        './src/Livewire/**/*.php',
        './src/Filament/**/*.php',
    ],

    darkMode: 'class',

    theme: {
        extend: {
            colors: {
                custom: {
                    50: 'rgba(var(--c-50), <alpha-value>)',
                    100: 'rgba(var(--c-100), <alpha-value>)',
                    200: 'rgba(var(--c-200), <alpha-value>)',
                    300: 'rgba(var(--c-300), <alpha-value>)',
                    400: 'rgba(var(--c-400), <alpha-value>)',
                    500: 'rgba(var(--c-500), <alpha-value>)',
                    600: 'rgba(var(--c-600), <alpha-value>)',
                    700: 'rgba(var(--c-700), <alpha-value>)',
                    800: 'rgba(var(--c-800), <alpha-value>)',
                    900: 'rgba(var(--c-900), <alpha-value>)',
                    950: 'rgba(var(--c-950), <alpha-value>)',
                },
                danger: {
                    50: 'rgba(var(--danger-50), <alpha-value>)',
                    100: 'rgba(var(--danger-100), <alpha-value>)',
                    200: 'rgba(var(--danger-200), <alpha-value>)',
                    300: 'rgba(var(--danger-300), <alpha-value>)',
                    400: 'rgba(var(--danger-400), <alpha-value>)',
                    500: 'rgba(var(--danger-500), <alpha-value>)',
                    600: 'rgba(var(--danger-600), <alpha-value>)',
                    700: 'rgba(var(--danger-700), <alpha-value>)',
                    800: 'rgba(var(--danger-800), <alpha-value>)',
                    900: 'rgba(var(--danger-900), <alpha-value>)',
                    950: 'rgba(var(--danger-950), <alpha-value>)',
                },
                primary: {
                    50: 'rgba(var(--primary-50), <alpha-value>)',
                    100: 'rgba(var(--primary-100), <alpha-value>)',
                    200: 'rgba(var(--primary-200), <alpha-value>)',
                    300: 'rgba(var(--primary-300), <alpha-value>)',
                    400: 'rgba(var(--primary-400), <alpha-value>)',
                    500: 'rgba(var(--primary-500), <alpha-value>)',
                    600: 'rgba(var(--primary-600), <alpha-value>)',
                    700: 'rgba(var(--primary-700), <alpha-value>)',
                    800: 'rgba(var(--primary-800), <alpha-value>)',
                    900: 'rgba(var(--primary-900), <alpha-value>)',
                    950: 'rgba(var(--primary-950), <alpha-value>)',
                },
                success: {
                    50: 'rgba(var(--success-50), <alpha-value>)',
                    100: 'rgba(var(--success-100), <alpha-value>)',
                    200: 'rgba(var(--success-200), <alpha-value>)',
                    300: 'rgba(var(--success-300), <alpha-value>)',
                    400: 'rgba(var(--success-400), <alpha-value>)',
                    500: 'rgba(var(--success-500), <alpha-value>)',
                    600: 'rgba(var(--success-600), <alpha-value>)',
                    700: 'rgba(var(--success-700), <alpha-value>)',
                    800: 'rgba(var(--success-800), <alpha-value>)',
                    900: 'rgba(var(--success-900), <alpha-value>)',
                    950: 'rgba(var(--success-950), <alpha-value>)',
                },
            },
        },
    },

    // These classes should already present in a panel's CSS, so they are not needed,
    // and in some cases they will conflict with the panel's CSS.
    blocklist: [
        'sr-only',
        'visible',
        'relative',
        'inline-block',
        'inline',
        'flex',
        'inline-flex',
        'grid',
        'min-h-screen',
        'flex-1',
        'flex-shrink-0',
        'text-sm',
        'text-base',
        'text-lg',
        'text-xl',
        'text-xs',
        'text-2xl',
        'font-serif',
        'font-mono',
        'font-sans',
        'font-light',
        'font-normal',
        'font-medium',
        'font-extrabold',
        'font-black',
        'font-bold',
        'font-semibold',
        'font-thin',
        'font-extralight',
        'text-center',
        'text-left',
        'fill-current',
        'overflow-hidden',
        'flex-col',
        'flex-wrap',
        'items-start',
        'items-center',
        'justify-center',
        'justify-between',
        'list-disc',
        'list-inside',
        'animate-spin',
        'cursor-pointer',
        'w-auto',
        'w-full',
        'shrink-0',
        'h-4',
        'h-5',
        'h-6',
        'h-8',
        'w-4',
        'w-5',
        'w-6',
        'w-8',
    ],
}
